"""empty message

Revision ID: 22f1efe9decb
Revises: cc0795865f18
Create Date: 2024-08-03 21:25:56.295913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f1efe9decb'
down_revision = 'cc0795865f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.drop_index('ix_users_username')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_users_username', ['username'], unique=1)
        batch_op.alter_column('email',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
