"""empty message

Revision ID: 37189279deb5
Revises: 6d7a79017a02
Create Date: 2024-08-04 20:23:10.018461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37189279deb5'
down_revision = '6d7a79017a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('container_id', sa.String(length=64), nullable=True))
        batch_op.drop_column('conatiner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conatiner_id', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('container_id')

    # ### end Alembic commands ###
