"""empty message

Revision ID: 6d7a79017a02
Revises: 83134af1f938
Create Date: 2024-08-04 20:19:57.754201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7a79017a02'
down_revision = '83134af1f938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_name', sa.String(length=100), nullable=False),
    sa.Column('image_id', sa.String(length=255), nullable=False),
    sa.Column('image_tag', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conatiner_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('container_images')
    # ### end Alembic commands ###
