"""empty message

Revision ID: 83134af1f938
Revises: 313658fc8b3f
Create Date: 2024-08-04 20:17:14.258933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83134af1f938'
down_revision = '313658fc8b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conatiner_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_images', schema=None) as batch_op:
        batch_op.drop_column('conatiner_id')

    # ### end Alembic commands ###
