"""empty message

Revision ID: b18a314e4962
Revises: d07e0aea34a0
Create Date: 2024-08-04 20:28:01.009745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18a314e4962'
down_revision = 'd07e0aea34a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_images', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
