"""empty message

Revision ID: d07e0aea34a0
Revises: e7bcf51a8946
Create Date: 2024-08-04 20:27:29.785057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07e0aea34a0'
down_revision = 'e7bcf51a8946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_images', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
